<a href="https://colab.research.google.com/github/saisudhanv/ML-Practice/blob/main/Handling_Date_and_Time.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [6]:
date = pd.read_csv('/content/orders.csv')

In [7]:
time = pd.read_csv('/content/messages.csv')

In [8]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [9]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [10]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [11]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

Working with data

In [12]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [13]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

**Extract year**

In [15]:
date['date_year'] = date['date'].dt.year

In [16]:
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

In [17]:
date.sample(5)

          date  product_id  city_id  orders  date_year
216 2019-12-13        3493       26       9       2019
853 2019-08-11        7430        1       1       2019
53  2019-12-04        5193       16       2       2019
6   2018-11-21        1282       26       1       2018
384 2018-12-27        2367        0       2       2018

**Extract Month**

In [18]:
date['date_month_no'] = date['date'].dt.month

In [19]:
date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [20]:
date['date_month_name'] = date['date'].dt.month_name()

In [21]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

**Extract Days**

In [22]:
date['date_day'] = date['date'].dt.day

In [23]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [24]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek

In [25]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [26]:
# day of week - name
date['date_dow_name'] = date['date'].dt.day_name()

In [27]:
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [34]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0) # Is weekend
# date['date_is_weekend'] = ...: This part is assigning values to a new column named date_is_weekend in your date DataFrame.
# np.where(...): This is a NumPy function that performs a conditional check. It's similar to an 'if-else' statement. It takes three arguments: a condition, a value to return if the condition is true, and a value to return if the condition is false.
# date['date_dow_name'].isin(['Sunday', 'Saturday']): This is the condition. It checks each entry in the date_dow_name column to see if it is either 'Sunday' or 'Saturday'.
# 1: If the day name is 'Sunday' or 'Saturday' (i.e., the condition is true), the date_is_weekend column for that row will be set to 1.
# 0: If the day name is neither 'Sunday' nor 'Saturday' (i.e., the condition is false), the date_is_weekend column for that row will be set to 0.

In [32]:
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

**Extract week of the year**

In [36]:
date['date_week'] = date['date'].dt.isocalendar().week

In [37]:
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

**Extract Quarter**

In [38]:
date['quarter'] = date['date'].dt.quarter

In [39]:
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

**Extract Semester**

In [40]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

In [41]:
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

**Extract Time elapsed between dates**

In [42]:
import datetime

today = datetime.datetime.today()

In [43]:
today

datetime.datetime(2026, 3, 14, 10, 21, 41, 360788)

In [44]:
today - date['date']

0     2286 days 10:21:41.360788
1     2768 days 10:21:41.360788
2     2699 days 10:21:41.360788
3     2401 days 10:21:41.360788
4     2624 days 10:21:41.360788
                 ...
995   2714 days 10:21:41.360788
996   2655 days 10:21:41.360788
997   2503 days 10:21:41.360788
998   2568 days 10:21:41.360788
999   2342 days 10:21:41.360788
Name: date, Length: 1000, dtype: timedelta64[ns]

In [45]:
(today - date['date']).dt.days

0      2286
1      2768
2      2699
3      2401
4      2624
       ...
995    2714
996    2655
997    2503
998    2568
999    2342
Name: date, Length: 1000, dtype: int64

In [47]:
# Months passed

np.round((today - date['date']).dt.days / 30.4375, 0)

0      75.0
1      91.0
2      89.0
3      79.0
4      86.0
       ...
995    89.0
996    87.0
997    82.0
998    84.0
999    77.0
Name: date, Length: 1000, dtype: float64

In [48]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [49]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [50]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [51]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

In [52]:
time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

**Extract time part**

In [53]:
time['time'] = time['date'].dt.time

In [54]:
time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

**Time difference**

In [55]:
today - time['date']

0     4472 days 09:31:41.360788
1     4336 days 10:41:41.360788
2     4822 days 10:00:41.360788
3     4124 days 09:50:41.360788
4     4521 days 11:10:41.360788
                 ...
995   5111 days 09:31:41.360788
996   4432 days 11:07:41.360788
997   4897 days 10:44:41.360788
998   5013 days 10:47:41.360788
999   4285 days 10:56:41.360788
Name: date, Length: 1000, dtype: timedelta64[ns]

In [56]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.864151e+08
1      3.746689e+08
2      4.166568e+08
3      3.563490e+08
4      3.906546e+08
           ...
995    4.416247e+08
996    3.829649e+08
997    4.231395e+08
998    4.331621e+08
999    3.702634e+08
Name: date, Length: 1000, dtype: float64

In [57]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.440252e+06
1      6.244482e+06
2      6.944281e+06
3      5.939151e+06
4      6.510911e+06
           ...
995    7.360412e+06
996    6.382748e+06
997    7.052325e+06
998    7.219368e+06
999    6.171057e+06
Name: date, Length: 1000, dtype: float64

In [58]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      107337.528156
1      104074.694822
2      115738.011489
3       98985.844822
4      108515.178156
           ...
995    122673.528156
996    106379.128156
997    117538.744822
998    120322.794822
999    102850.944822
Name: date, Length: 1000, dtype: float64